site_name: Interview Preparation
site_url: https://leninjoseph.github.io/interview_preparation/
theme:
  name: material
  features:
    - navigation.tabs
  palette:
    primary: indigo
    accent: indigo
  navigation:
    location: left

nav:
  - Home: index.md
  - React:
      - Introduction: react/index.md
      - Learn JS: react/react_docs/js_learn.md
      - Learn React: react/react_docs/react_learn.md
      - Technical Topics: react/react_docs/technical_topics.md
      - Behaviral Topics: react/react_docs/behavioral_questions.md
  - Python:
      - Introduction: python/index.md
      - Python Basics: python/python_docs/basic_concepts.md
      - OOPs: python/python_docs/oops.md
plugins:
  - search
