site_name: Interview Preparation
site_url: https://leninjoseph.github.io/interview_preparation/
theme:
  name: material
  features:
    - navigation.tabs
  palette:
    primary: indigo
    accent: indigo
  navigation:
    location: left

nav:
  - Home: index.md
  - React:
      - Introduction: react/index.md
      - Learn JS: react/react_docs/js_learn.md
      - Learn React: react/react_docs/react_learn.md
      - Technical Topics: react/react_docs/technical_topics.md
      - Behaviral Topics: react/react_docs/behavioral_questions.md
  - Python:
      - Introduction: python/index.md
      - Python Basics: python/python_docs/basic_concepts.md
      - OOPs: python/python_docs/oops.md
  - Design Patterns:
      - Introduction: design_patterns/index.md
      - Real Time Examples:
          - API Gateway Pattern: design_patterns/real_time_patterns/api_gateway_pattern.md
          - Dependancy Injection Pattern: design_patterns/real_time_patterns/dependancy_injection_pattern.md
          - Factory Pattern: design_patterns/real_time_patterns/factory_pattern.md
          - Rule Engine Pattern: design_patterns/real_time_patterns/rule_engine_pattern.md
          - Template Method Pattern: design_patterns/real_time_patterns/template_method_pattern.md
          - Transformer Pattern: design_patterns/real_time_patterns/transformer_pattern.md
          - Resolver Pattern: design_patterns/real_time_patterns/resolver_pattern.md
plugins:
  - search
